import {BackSpeedSet} from "./events/BackSpeedSet";
import {BackDelay} from "./events/BackDelay";
import {EnemiesLoadShapes} from "./events/EnemiesLoadShapes";
import {Enemy} from "./events/Enemy";
import {StarSwitch} from "./events/StarSwitch";
import {LevelEnd} from "./events/LevelEnd";
import {EnemiesSwitch} from "./events/EnemiesSwitch";
import {ShowMessage} from "./events/ShowMessage";
import {EnemiesGlobalMove} from "./events/EnemiesGlobalMove";
import {BackOverSwitch} from "./events/BackOverSwitch";
import {EnemiesGlobalAnimate} from "./events/EnemiesGlobalAnimate";
import {EnemiesGlobalDamage} from "./events/EnemiesGlobalDamage";
import {EnemySmallAdjustPos} from "./events/EnemySmallAdjustPos";
import {EnemiesOverSwitch} from "./events/EnemiesOverSwitch";
import {EnemiesFireOverride} from "./events/EnemiesFireOverride";
import {EnemySpawn} from "./events/EnemySpawn";
import {LevelEnemiesFrequency} from "./events/LevelEnemiesFrequency";
import {EventsJump} from "./events/EventsJump";
import {EnemiesGlobalLinkNum} from "./events/EnemiesGlobalLinkNum";
import {EnemiesContinualDamage} from "./events/EnemiesContinualDamage";
import {EnemiesReset} from "./events/EnemiesReset";
import {LevelFilters} from "./events/LevelFilters";
import {LevelDifficulty} from "./events/LevelDifficulty";
import {EventsForcedForward} from "./events/EventsForcedForward";
import {EnemySpecialAssign} from "./events/EnemySpecialAssign";
import {BackJump} from "./events/BackJump";
import {EnemyBossLinkNum} from "./events/EnemyBossLinkNum";
import {BackWrap} from "./events/BackWrap";
import {EventBase} from "./EventBase";

class Unsupported extends EventBase {}

export enum TyEventType {
    UNSUPPORTED = 0,
    STAR_FIELD_SPEED = 1,
    BACK_SPEED_SET = 2,
    BACK_DELAY = 3,
    BACK_DELAY_TYPE = 4,
    ENEMIES_LOAD_SHAPES = 5,
    ENEMY_GROUND_25 = 6,
    ENEMY_TOP_50 = 7,
    STAR_OFF = 8,
    STAR_ON = 9,
    ENEMY_GROUND_75 = 10,
    LEVEL_END = 11,
    ENEMY_GROUND_4x4 = 12, //the big one
    ENEMIES_OFF = 13,
    ENEMIES_ON = 14,
    ENEMY_SKY_0 = 15,
    SHOW_MESSAGE = 16,
    ENEMY_GROUND_BOTTOM_25 = 17,
    ENEMY_SKY_BOTTOM_0 = 18,
    ENEMIES_GLOBAL_MOVE_0 = 19,
    ENEMIES_GLOBAL_MOVE_1 = 20,
    BACK_3_OVER_1 = 21,
    BACK_3_OVER_OFF = 22,
    ENEMY_SKY_BOTTOM_50 = 23,
    ENEMIES_GLOBAL_ANIMATE = 24,
    ENEMIES_GLOBAL_DAMAGE = 25,
    ENEMY_SMALL_ADJUST_POS = 26,
    ENEMIES_GLOBAL_MOVE_2 = 27,
    ENEMIES_TOP_OVER_OFF = 28,
    ENEMIES_TOP_OVER_ON  = 29,
    BACK_SPEED_SET_2 = 30,
    ENEMIES_FIRE_OVERRIDE = 31,
    ENEMY_TOP_BOTTOM_50 = 32,
    ENEMY_SPAWN = 33,
    MUSIC_FADE_ = 34,
    MUSIC_TRACK_ = 35,
    LEVEL_READY_TO_END = 36,
    LEVEL_ENEMIES_FREQUENCY = 37,
    EVENTS_JUMP = 38,
    ENEMIES_GLOBAL_LINK_NUM = 39,
    ENEMIES_CONTINUAL_DAMAGE = 40,
    ENEMIES_RESET = 41,
    BACK_3_OVER_2 = 42,
    BACK_2_OVER = 43,
    LEVEL_FILTERS = 44,
    ENEMY_SPAWN_ARCADE = 45,
    LEVEL_DIFFICULTY = 46,
    ENEMIES_GLOBAL_DAMAGE_ = 47,
    BACK_2_NOT_TRANSPARENT = 48,
    ENEMY_CREATE_0 = 49,
    ENEMY_CREATE_1 = 50,
    ENEMY_CREATE_2 = 51,
    ENEMY_CREATE_3 = 52,
    EVENTS_FORCED_FORWARD = 53,
    EVENTS_JUMP_WITH_RETURN = 54,
    ENEMIES_GLOBAL_MOVE_3 = 55,
    ENEMY_GROUND_2_BOTTOM = 56,
    EVENTS_JUMP_SUPER_ENEMY = 57,
    WTF_58 = 58,//??
    WTF_59 = 59,//??
    ENEMY_SPECIAL_ASSIGN = 60,
    EVENTS_JUMP_GLOBAL_FLAG = 61,
    MUSIC_EFFECT = 62,
    EVENTS_JUMP_SINGLE_PLAYER = 63,
    SMOOTHIES = 64,
    BACK_3_X1 = 65,
    EVENTS_JUMP_DIFFICULTY = 66,
    EVENTS_JUMP_TIMER = 67,
    RANDOM_EXPLOSIONS_SWITCH = 68,
    IMPREVIOUS_TICKS = 69,
    EVENTS_JUMP_OPTIONAL = 70,
    EVENTS_JUMP_SECRET = 71,
    BACK_3_X1B = 72,
    ENEMIES_SKY_OVER_SWITCH = 73,
    ENEMIES_GLOBAL_MOVE_4 = 74,
    WTF_75 = 75,
    EVENTS_JUMP_RETURN = 76,
    BACKGROUND_JUMP = 77,
    GALAGA_SHOT_FREQUENCY_INC = 78,
    BOSS_BAR_LINK_NUM_SET = 79,
    EVENTS_JUMP_MULTIPLAYER = 80,
    BACKGROUND_WRAP = 81,
    PLAYER_SPECIAL_WEAPON_SET = 82,

}

export const TyEventKindMap = {
    [TyEventType.UNSUPPORTED]: Unsupported,
    [TyEventType.BACK_SPEED_SET]: BackSpeedSet,
    [TyEventType.BACK_DELAY]: BackDelay,
    [TyEventType.BACK_DELAY_TYPE]: BackDelay,
    [TyEventType.ENEMIES_LOAD_SHAPES]: EnemiesLoadShapes,
    [TyEventType.ENEMY_GROUND_25]: Enemy,
    [TyEventType.ENEMY_TOP_50]: Enemy,
    [TyEventType.ENEMY_GROUND_75]: Enemy,
    [TyEventType.STAR_OFF]: StarSwitch,
    [TyEventType.STAR_ON]: StarSwitch,
    [TyEventType.LEVEL_END]: LevelEnd,
    [TyEventType.ENEMY_GROUND_4x4]: Enemy,
    [TyEventType.ENEMIES_OFF]: EnemiesSwitch,
    [TyEventType.ENEMIES_ON]: EnemiesSwitch,
    [TyEventType.ENEMY_SKY_0]: Enemy,
    [TyEventType.SHOW_MESSAGE]: ShowMessage,
    [TyEventType.ENEMY_GROUND_BOTTOM_25]: Enemy,
    [TyEventType.ENEMY_SKY_BOTTOM_0]: Enemy,
    [TyEventType.ENEMIES_GLOBAL_MOVE_0]: EnemiesGlobalMove,
    [TyEventType.ENEMIES_GLOBAL_MOVE_1]: EnemiesGlobalMove,
    [TyEventType.BACK_3_OVER_1]: BackOverSwitch,
    [TyEventType.BACK_3_OVER_OFF]: BackOverSwitch,
    [TyEventType.ENEMY_SKY_BOTTOM_50]: Enemy,
    [TyEventType.ENEMIES_GLOBAL_ANIMATE]: EnemiesGlobalAnimate,
    [TyEventType.ENEMIES_GLOBAL_DAMAGE]: EnemiesGlobalDamage,
    [TyEventType.ENEMY_SMALL_ADJUST_POS]: EnemySmallAdjustPos,
    [TyEventType.ENEMIES_GLOBAL_MOVE_2]: EnemiesGlobalMove,
    [TyEventType.ENEMIES_TOP_OVER_ON]: EnemiesOverSwitch,
    [TyEventType.ENEMIES_TOP_OVER_OFF]: EnemiesOverSwitch,
    [TyEventType.BACK_SPEED_SET_2]: BackSpeedSet,
    [TyEventType.ENEMIES_FIRE_OVERRIDE]: EnemiesFireOverride,
    [TyEventType.ENEMY_TOP_BOTTOM_50]: Enemy,
    [TyEventType.ENEMY_SPAWN]: EnemySpawn,
    [TyEventType.LEVEL_READY_TO_END]: LevelEnd,
    [TyEventType.LEVEL_ENEMIES_FREQUENCY]: LevelEnemiesFrequency,
    [TyEventType.EVENTS_JUMP]: EventsJump,
    [TyEventType.ENEMIES_GLOBAL_LINK_NUM]: EnemiesGlobalLinkNum,
    [TyEventType.ENEMIES_CONTINUAL_DAMAGE]: EnemiesContinualDamage,
    [TyEventType.ENEMIES_RESET]: EnemiesReset,
    [TyEventType.BACK_3_OVER_2]: BackOverSwitch,
    [TyEventType.BACK_2_OVER]: BackOverSwitch,
    [TyEventType.LEVEL_FILTERS]: LevelFilters,
    [TyEventType.LEVEL_DIFFICULTY]: LevelDifficulty,
    [TyEventType.ENEMIES_GLOBAL_DAMAGE_]: EnemiesGlobalDamage,
    [TyEventType.ENEMY_CREATE_0]: Enemy,
    [TyEventType.ENEMY_CREATE_1]: Enemy,
    [TyEventType.ENEMY_CREATE_2]: Enemy,
    [TyEventType.ENEMY_CREATE_3]: Enemy,
    [TyEventType.EVENTS_FORCED_FORWARD]: EventsForcedForward,
    [TyEventType.EVENTS_JUMP_WITH_RETURN]: EventsJump,
    [TyEventType.ENEMIES_GLOBAL_MOVE_3]: EnemiesGlobalMove,
    [TyEventType.ENEMY_GROUND_2_BOTTOM]: Enemy,
    [TyEventType.EVENTS_JUMP_SUPER_ENEMY]: EventsJump,
    [TyEventType.ENEMY_SPECIAL_ASSIGN]: EnemySpecialAssign,
    [TyEventType.EVENTS_JUMP_GLOBAL_FLAG]: EventsJump,
    [TyEventType.EVENTS_JUMP_SINGLE_PLAYER]: EventsJump,
    [TyEventType.EVENTS_JUMP_DIFFICULTY]: EventsJump,
    [TyEventType.EVENTS_JUMP_TIMER]: EventsJump,
    [TyEventType.EVENTS_JUMP_OPTIONAL]: EventsJump,
    [TyEventType.EVENTS_JUMP_SECRET]: EventsJump,
    [TyEventType.ENEMIES_SKY_OVER_SWITCH]: EnemiesOverSwitch,
    [TyEventType.ENEMIES_GLOBAL_MOVE_4]: EnemiesGlobalMove,
    [TyEventType.EVENTS_JUMP_RETURN]: EventsJump,
    [TyEventType.BACKGROUND_JUMP]: BackJump,
    [TyEventType.BOSS_BAR_LINK_NUM_SET]: EnemyBossLinkNum,
    [TyEventType.EVENTS_JUMP_MULTIPLAYER]: EventsJump,
    [TyEventType.BACKGROUND_WRAP]: BackWrap,
}

export type TyEventTypeMap = {
    UNSUPPORTED: Unsupported,
    BACK_SPEED_SET: BackSpeedSet,
    BACK_DELAY: BackDelay,
    BACK_DELAY_TYPE: BackDelay,
    ENEMIES_LOAD_SHAPES: EnemiesLoadShapes,
    ENEMY_GROUND_25: Enemy,
    ENEMY_TOP_50: Enemy,
    ENEMY_GROUND_75: Enemy,
    STAR_OFF: StarSwitch,
    STAR_ON: StarSwitch,
    LEVEL_END: LevelEnd,
    ENEMY_GROUND_4x4: Enemy,
    ENEMIES_OFF: EnemiesSwitch,
    ENEMIES_ON: EnemiesSwitch,
    ENEMY_SKY_0: Enemy,
    SHOW_MESSAGE: ShowMessage,
    ENEMY_GROUND_BOTTOM_25: Enemy,
    ENEMY_SKY_BOTTOM_0: Enemy,
    ENEMIES_GLOBAL_MOVE_0: EnemiesGlobalMove,
    ENEMIES_GLOBAL_MOVE_1: EnemiesGlobalMove,
    BACK_3_OVER_1: BackOverSwitch,
    BACK_3_OVER_OFF: BackOverSwitch,
    ENEMY_SKY_BOTTOM_50: Enemy,
    ENEMIES_GLOBAL_ANIMATE: EnemiesGlobalAnimate,
    ENEMIES_GLOBAL_DAMAGE: EnemiesGlobalDamage,
    ENEMY_SMALL_ADJUST_POS: EnemySmallAdjustPos,
    ENEMIES_GLOBAL_MOVE_2: EnemiesGlobalMove,
    ENEMIES_TOP_OVER_ON: EnemiesOverSwitch,
    ENEMIES_TOP_OVER_OFF: EnemiesOverSwitch,
    BACK_SPEED_SET_2: BackSpeedSet,
    ENEMIES_FIRE_OVERRIDE: EnemiesFireOverride,
    ENEMY_TOP_BOTTOM_50: Enemy,
    ENEMY_SPAWN: EnemySpawn,
    LEVEL_READY_TO_END: LevelEnd,
    LEVEL_ENEMIES_FREQUENCY: LevelEnemiesFrequency,
    EVENTS_JUMP: EventsJump,
    ENEMIES_GLOBAL_LINK_NUM: EnemiesGlobalLinkNum,
    ENEMIES_CONTINUAL_DAMAGE: EnemiesContinualDamage,
    ENEMIES_RESET: EnemiesReset,
    BACK_3_OVER_2: BackOverSwitch,
    BACK_2_OVER: BackOverSwitch,
    LEVEL_FILTERS: LevelFilters,
    LEVEL_DIFFICULTY: LevelDifficulty,
    ENEMIES_GLOBAL_DAMAGE_: EnemiesGlobalDamage,
    ENEMY_CREATE_0: Enemy,
    ENEMY_CREATE_1: Enemy,
    ENEMY_CREATE_2: Enemy,
    ENEMY_CREATE_3: Enemy,
    EVENTS_FORCED_FORWARD: EventsForcedForward,
    EVENTS_JUMP_WITH_RETURN: EventsJump,
    ENEMIES_GLOBAL_MOVE_3: EnemiesGlobalMove,
    ENEMY_GROUND_2_BOTTOM: Enemy,
    EVENTS_JUMP_SUPER_ENEMY: EventsJump,
    ENEMY_SPECIAL_ASSIGN: EnemySpecialAssign,
    EVENTS_JUMP_GLOBAL_FLAG: EventsJump,
    EVENTS_JUMP_SINGLE_PLAYER: EventsJump,
    EVENTS_JUMP_DIFFICULTY: EventsJump,
    EVENTS_JUMP_TIMER: EventsJump,
    EVENTS_JUMP_OPTIONAL: EventsJump,
    EVENTS_JUMP_SECRET: EventsJump,
    ENEMIES_SKY_OVER_SWITCH: EnemiesOverSwitch,
    ENEMIES_GLOBAL_MOVE_4: EnemiesGlobalMove,
    EVENTS_JUMP_RETURN: EventsJump,
    BACKGROUND_JUMP: BackJump,
    BOSS_BAR_LINK_NUM_SET: EnemyBossLinkNum,
    EVENTS_JUMP_MULTIPLAYER: EventsJump,
    BACKGROUND_WRAP: BackWrap,
}


export type TyEventKey = keyof typeof TyEventType;
export type CreatedTyEvent<T extends TyEventKey> = T extends keyof TyEventTypeMap ? TyEventTypeMap[T] : Unsupported;
